version: '3'
services:
#mssql docker
  tvojfilm-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - TvojFilmNet

  tvojfilm-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=tvojfilm-sql,1433;Database=IB170099;User=sa;Password=QWElkj132!;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5171:5171
    networks:
      - TvojFilmNet     
    links:
      - tvojfilm-sql
    depends_on:
      - tvojfilm-sql
      
networks:
  TvojFilmNet:
    driver: bridge 